# Generated by Django 6.0.2 on 2026-04-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='order_list',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='order_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items_ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='picking_time',
            field=models.CharField(default='15 min', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
