# Generated by Django 6.0.7 on 2026-08-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(default='full', max_length=20),
        ),
    ]
