# Generated by Django 6.0.7 on 2026-09-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_order_amount_paid_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deals/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(),
        ),
    ]
