# Generated by Django 6.0.7 on 2026-09-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_alter_deal_image_alter_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('chai', 'Chai & Qehwa'), ('meetha', 'Meetha Paratha'), ('masala', 'Masalay Wala Items'), ('omelette', 'Omelettes & Snacks')], default='chai', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
