# Generated by Django 6.0.7 on 2026-09-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_menuitem_category_alter_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('prepared', 'Prepared'), ('picked_up', 'Picked Up')], default='pending', max_length=20),
        ),
    ]
