# Generated by Django 6.0.7 on 2026-09-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('prepared', 'Prepared'), ('picked_up', 'Picked Up'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
